apiVersion: v1
kind: ConfigMap
metadata:
  name: bluemix-target
  labels:
    app: bluecompute
    tier: config
data:
  bluemix-api-endpoint: api.ng.bluemix.net
  bluemix-org: PUT_YOUR_ORG_HERE
  bluemix-space: PUT_YOUR_SPACE_HERE
  bluemix-registry: registry.ng.bluemix.net
  bluemix-registry-namespace: PUT_YOUR_REGISTRY_NAMESPACE_HERE
  kube-cluster-name: PUT_YOUR_CLUSTER_NAME_HERE
